#!/bin/sh
alias ka="killall" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	calcurse="calcurse -D ~/.config/calcurse" \
	magit="nvim -c Magit" \
	p="trizen" \
	SS="sudo systemctl" \
	f="$FILE" \
	g="git" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR" \
	Sv="sudo $EDITOR" \
	x="sxiv -ft *" \
	q="exit" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="p -Syu --noconfirm --noedit; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	clr="clear" \
	ffmpeg="ffmpeg -hide_banner" \
	upgm="mailsync" \
	update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

case "$(cat /etc/*-release | grep PRETTY_NAME | awk -F'"' '{print $2}')" in
	void) alias p="sudo xbps-install" \
		pu="sudo xbps-remove" \
		upc="sudo xbps-install -Syu; pkill -RTMIN+8 i3blocks" ;;
esac

se() { du -a ~/.scripts/* ~/.config/* | awk '{print $2}' | fzf | xargs  -r $EDITOR ;}
vf() { fzf | xargs -r -I % $EDITOR % ;}
