#!/bin/sh
#                   _      _
#  _   _ _   _ _ __(_)_ __(_) ___ ___
# | | | | | | | '__| | '__| |/ __/ _ \
# | |_| | |_| | |  | | |  | | (_|  __/
#  \__, |\__,_|_|  |_|_|  |_|\___\___|
#  |___/
#
# 06/06/2022

# Statusbar
polybar default &

# Remaps
remaps &

# Keybindings
pgrep -x sxhkd >/dev/null || sxhkd &

# Use right cursor
xsetroot -cursor_name left_ptr

# Set the background
setbg -r &

# Start `dunst` for notifications
dunst &

# Mouse invisibility
unclutter &

# Basic Definitions
bspc config border_width	2
bspc config window_gap		15
bspc config top_padding 	24

bspc config split_ratio		0.52
bspc config borderless_monocle	true
bspc config gapless_monocle	true

# Pointer settings
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc desktop -f 1

# `pywal` colours
source ~/.cache/wal/colors.sh

bspc config active_border_color   $background
bspc config normal_border_color   $background
bspc config focused_border_color  $foreground
bspc config presel_feedback_color $color4

# Dropdown
bspc rule -a ddterm sticky=on state=floating hidden=on rectangle=1500x500+210+0
bspc rule -a ddmixer sticky=on state=floating hidden=on rectangle=1500x500+210+0
bspc rule -a ddcalc sticky=on state=floating hidden=on rectangle=1500x500+210+0

# Zathura
bspc rule -a Zathura state=tiled
