#!/bin/sh
polybar default &

# Remaps
remaps &

# Keybindings
sxhkd &

source ~/.cache/wal/colors.sh

bspc config focus_follows_pointer true
bspc config border_width	2
bspc config window_gap		15

bspc config split_ratio		0.52
bspc config borderless_monocle	true
bspc config gapless_monocle	true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc desktop -f 1

bspc config active_border_color   $background
bspc config normal_border_color   $background
bspc config focused_border_color  $foreground
bspc config presel_feedback_color $color4

bspc rule -a ddterm sticky=on state=floating hidden=on
bspc rule -a ddmixer sticky=on state=floating hidden=on
bspc rule -a ddcalc sticky=on state=floating hidden=on
